from typing import Protocol
from uuid import UUID

from app.domain.entities import (
    AnalysisRun,
    Clause,
    ComplianceFinding,
    Contract,
    DocumentChunk,
    QAResult,
    RiskFinding,
    Summary,
)


class ContractRepository(Protocol):
    async def create(self, contract: Contract) -> Contract: ...
    async def get_by_id(self, contract_id: UUID) -> Contract | None: ...
    async def list_all(self, skip: int = 0, limit: int = 50) -> list[Contract]: ...
    async def update_status(self, contract_id: UUID, status: str) -> None: ...


class ChunkRepository(Protocol):
    async def create_many(self, chunks: list[DocumentChunk]) -> list[DocumentChunk]: ...
    async def get_by_contract(self, contract_id: UUID) -> list[DocumentChunk]: ...


class AnalysisRepository(Protocol):
    async def create_run(self, run: AnalysisRun) -> AnalysisRun: ...
    async def update_run(self, run: AnalysisRun) -> AnalysisRun: ...
    async def get_latest_run(self, contract_id: UUID) -> AnalysisRun | None: ...
    async def save_clauses(self, clauses: list[Clause]) -> None: ...
    async def save_risks(self, risks: list[RiskFinding]) -> None: ...
    async def save_compliance(self, findings: list[ComplianceFinding]) -> None: ...
    async def save_summary(self, summary: Summary) -> None: ...
    async def get_clauses(self, contract_id: UUID) -> list[Clause]: ...
    async def get_risks(self, contract_id: UUID) -> list[RiskFinding]: ...
    async def get_compliance(self, contract_id: UUID) -> list[ComplianceFinding]: ...
    async def get_summary(self, contract_id: UUID) -> Summary | None: ...
    async def save_qa(self, contract_id: UUID, question: str, answer: str, sources: list) -> None: ...


class VectorStore(Protocol):
    async def add_chunks(self, contract_id: UUID, chunks: list[DocumentChunk]) -> None: ...
    async def search(self, contract_id: UUID, query: str, top_k: int) -> list[dict]: ...
    async def delete_by_contract(self, contract_id: UUID) -> None: ...


class LLMClient(Protocol):
    async def chat(self, system_prompt: str, user_prompt: str) -> str: ...
    async def embed(self, texts: list[str]) -> list[list[float]]: ...


class AnalysisGraph(Protocol):
    async def run(self, contract_id: UUID, full_text: str, chunks: list[dict]) -> dict: ...


class DocumentParser(Protocol):
    def parse(self, file_path: str, mime_type: str) -> tuple[str, list[dict]]: ...
